### ISSUE TITLE
Improve formatting of generated YAML files

### ISSUE THREAD

**Issue by johndgiese** [innolitics/n2y#15]
The current YAML dumper dumps out long strings in a very ugly way. YAML supports nice folded strings, which we should use. See https://stackoverflow.com/questions/6432605/any-yaml-libraries-in-python-that-support-dumping-of-long-strings-as-block-liter for some ideas.

Also, it seems that curly quotes are expanded into unicode in an ugly way. I don't know if this is a PyYAML quirk or what. It would be nice if we didn't have a bunch of `\u2019` and `\u201C` codes in the generated output.

After addressing these two issues this string:

```yaml
- status_justification: No software description has been written.
  sources:
  - 2005/2021 Software
  - 2021 Software
  how_innolitics_can_help: We have a template that has recently been updated to reflect
    suggestions in the 2021 draft guidance. We can also review the final documents.
  description: "A clear high-level summary of the software\u2019s functionality, design,\
    \ inputs, and outputs including a description of how the software components relate\
    \ to the hardware aspects of the device. Graphical representations are helpful.\
    \ Version number for expected commercial version should be documented."
  how_to_fill_the_gap: This is a short document that typically includes a bunch of
    references to other documents. It should be quick to write.
  status: Incomplete
  name: Software Description
  content: null
```

would become

```yaml
- status_justification: No software description has been written.
  sources:
  - 2005/2021 Software
  - 2021 Software
  how_innolitics_can_help: We have a template that has recently been updated to reflect
    suggestions in the 2021 draft guidance. We can also review the final documents.
  description: |
   A clear high-level summary of the software's functionality, design,
   inputs, and outputs including a description of how the software components relate
   to the hardware aspects of the device. Graphical representations are helpful.
   Version number for expected commercial version should be documented."
  how_to_fill_the_gap: This is a short document that typically includes a bunch of
    references to other documents. It should be quick to write.
  status: Incomplete
  name: Software Description
  content: null
```
