### ISSUE TITLE
Test multiple Python versions in github workflow

### ISSUE THREAD

**Issue by notmatthancock** [innolitics/n2y#196]
If we are not explicitly requiring a specific Python version (and I don't think we should since this software is open source, where pinning to a specific minor version would feel too restrictive), then we should test multiple versions in the github workflow test runner.

This would be a simple update by [adding a matrix strategy block](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#using-multiple-python-versions) (for example):

```yaml
...
    strategy:
      matrix:
        python-version: ["pypy3.9", "pypy3.10", "3.9", "3.10", "3.11", "3.12"]
...
```
